# inherit from the proprietary version
-include vendor/lenovo/PB1770M/BoardConfigVendor.mk

# Board Informations
TARGET_OTA_ASSERT_DEVICE := PB1770M, PB1-770M
TARGET_NO_BOOTLOADER := true
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a53
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53
TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true
TARGET_BOARD_PLATFORM := msm8916
TARGET_BOARD_PLATFORM_GPU := qcom-adreno405

# no ant needed!


# Audio
AUDIO_FEATURE_ENABLED_KPI_OPTIMIZE := true
AUDIO_FEATURE_ENABLED_NEW_SAMPLE_RATE := true
BOARD_USES_ALSA_AUDIO := true
TARGET_QCOM_AUDIO_VARIANT := caf
#AUDIO_FEATURE_ENABLED_DS2_DOLBY_DAP := true
#DOLBY_DDP := true
#DOLBY_DAP := true
#AUDIO_FEATURE_ENABLED_AUDIO_AAC_OFFLOAD := true
#AUDIO_FEATURE_ENABLED_AUDIO_WMA_OFFLOAD := true

# Additional Setting
TARGET_BOOTLOADER_BOARD_NAME := MSM8916

# Camera 
TARGET_HAS_LEGACY_CAMERA_HAL1 := true

# Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_QCOM := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/lenovo/PB1770M/bluetooth
BLUETOOTH_HCI_USE_MCT := true


# Charger (imported from charger.mk)
BOARD_CHARGER_DISABLE_INIT_BLANK := true

# Additional Settings2
TARGET_QCOM_NO_FM_FIRMWARE := true
BOARD_HAVE_QCOM_FM := true
AUDIO_FEATURE_ENABLED_FM_POWER_OPT := true
BOARD_HAS_NO_SELECT_BUTTON := true

# Wifi related defines
WPA_SUPPLICANT_VERSION      := VER_0_8_X
BOARD_WLAN_DEVICE           := bcmdhd
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
BOARD_HOSTAPD_DRIVER        := NL80211
BOARD_HOSTAPD_PRIVATE_LIB   := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
WIFI_DRIVER_FW_PATH_PARAM   := "/sys/module/bcmdhd/parameters/firmware_path"
WIFI_DRIVER_FW_PATH_AP      := "/vendor/firmware/fw_bcmdhd_apsta.bin"
WIFI_DRIVER_FW_PATH_STA     := "/vendor/firmware/fw_bcmdhd.bin"


# Additional Settings3
BOARD_DTBTOOL_ARGS := -2
BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 androidboot.hardware=qcom msm_rtb.filter=0x237 ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci lpm_levels.sleep_disabled=1 earlyprintk androidboot.selinux=permissive
ENABLE_CPUSETS := true
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048 
BOARD_MKBOOTIMG_ARGS := --tags_offset 0x00000100 --ramdisk device/lenovo/PB1770M/ramdisk.img  --kernel device/lenovo/PB1770M/kernel --dt device/lenovo/PB1770M/dt.img

# BOARD_KERNEL_SEPARATED_DT := true
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_RAMDISK_OFFSET     := 0x01000000

# use custom mkbootimg (experimental)
# BOARD_CUSTOM_BOOTIMG_MK := device/lenovo/PB1770M/mkbootimg.mk

# Display
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
OVERRIDE_RS_DRIVER := libRSDriver_adreno.so
BOARD_USES_HWCOMPOSER := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
TARGET_USES_ION := true
TARGET_CONTINUOUS_SPLASH_ENABLED := true
USE_OPENGL_RENDERER := true

# kernel
# TARGET_KERNEL_SOURCE := kernel/lenovo/PB1770M
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_PREBUILT_KERNEL := device/lenovo/PB1770M/kernel
# maybe we are using zimage
#TARGET_USES_UNCOMPRESSED_KERNEL := true
TARGET_KERNEL_CONFIG := PB1770M_defconfig

# CMHW
BOARD_HARDWARE_CLASS += hardware/cyanogen/cmhw

# FILE SYSTEM TYPES
#BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true

# SELinux
BOARD_SEPOLICY_DIRS += device/lenovo/PB1770M/sepolicy
include device/qcom/sepolicy/sepolicy.mk

#signed
# TARGET_BOOTIMG_SIGNED := true

# charger
BOARD_CHARGER_ENABLE_SUSPEND := true
BOARD_CHARGER_SHOW_PERCENTAGE := true
# WITH_CM_CHARGER := true
TARGET_KEYMASTER_WAIT_FOR_QSEE := true

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2684354560 
BOARD_USERDATAIMAGE_PARTITION_SIZE := 27913075712
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_HW_DISK_ENCRYPTION := true
BOARD_PERSISTIMAGE_PARTITION_SIZE := 33554432

TARGET_SYSTEM_PROP += device/lenovo/PB1770M/system.prop

# Experimental Settings
# TARGET_PROVIDES_INIT_RC := true
# TARGET_INIT_VENDOR_LIB := libinit_msm
# TARGET_RECOVERY_DEVICE_MODULES := libinit_PB1770M
TARGET_PLATFORM_DEVICE_BASE := /devices/soc.0/

# Qualcomm support
ifneq ($(QCPATH),)
BOARD_USES_QCNE := true
TARGET_LDPRELOAD := libNimsWrap.so
endif
TARGET_POWERHAL_VARIANT := qcom
TARGET_RIL_VARIANT := caf 
BOARD_USES_QC_TIME_SERVICES := true
BOARD_USES_QCOM_HARDWARE := true

# RECOVERY
TARGET_RECOVERY_FSTAB := device/lenovo/PB1770M/rootdir/fstab.qcom
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
#BOARD_HAS_NO_MISC_PARTITION := true
BOARD_SUPPRESS_EMMC_WIPE := true
# GPS
BOARD_USES_QCOM_GPS := true
TARGET_NO_RPC := true

